"""Data schemas for Protocol RAG and replication planning.

Defines the structured evidence types used by the evidence store and
bioinformatics protocol tools. Every field follows the rule:
"原文未出现则不填，禁止凭空猜测" — if the source document does not
explicitly state a value, leave it empty/None rather than guessing.

Reference: BioCoreCoder 需求文档, Section 6.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Optional

from pydantic import BaseModel, Field


class EvidenceSpan(BaseModel):
    """A cited span of text from a source document.

    Every extracted fact (tool name, database version, parameter, etc.)
    must be traceable to one or more EvidenceSpans in the original document.
    """

    source_id: str
    source_type: str  # e.g. "protocol", "paper", "readme", "workflow_doc", "other"
    chunk_id: str = ""
    location: str = ""  # e.g. "chunk_003 lines 12-18" or "page 5 paragraph 2"
    text: str  # the actual cited text snippet


class ProtocolCard(BaseModel):
    """High-level summary of a bioinformatics protocol document.

    Captures the research goal, biological context, and pointers to the
    tasks and resources it references.  Fields not found in the source
    MUST be left as empty/None.
    """

    protocol_id: str
    title: str = ""
    source_type: str = "other"  # "protocol", "paper", "readme", "workflow_doc", "other"
    source_path: str = ""
    source_url: str = ""
    version_or_date: str = ""
    research_goal: str = ""
    organism: str = ""
    assay_type: str = ""  # e.g. "RNA-seq", "ChIP-seq", "ATAC-seq", "WGS"
    input_data: list[str] = Field(default_factory=list)
    output_data: list[str] = Field(default_factory=list)
    key_task_ids: list[str] = Field(default_factory=list)
    resource_ids: list[str] = Field(default_factory=list)
    missing_information: list[str] = Field(default_factory=list)
    evidence_spans: list[EvidenceSpan] = Field(default_factory=list)
    created_at: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )


class TaskCard(BaseModel):
    """A single computational task within a protocol.

    Describes one step of the workflow: what it does, what it consumes,
    what it produces, and what tools/databases/software it requires.
    """

    task_id: str
    protocol_id: str = ""  # filled by bio_extract_protocol; may be auto-populated by plan tool
    task_name: str
    task_type: str = "other"  # one of the recognized task categories below:
    # quality_control, alignment, quantification, differential_analysis,
    # enrichment, visualization, database_query, workflow_execution,
    # data_preprocessing, other
    description: str = ""
    inputs: list[str] = Field(default_factory=list)
    outputs: list[str] = Field(default_factory=list)
    tools_required: list[str] = Field(default_factory=list)
    databases_required: list[str] = Field(default_factory=list)
    software_required: list[str] = Field(default_factory=list)
    parameters: dict = Field(default_factory=dict)
    evidence_spans: list[EvidenceSpan] = Field(default_factory=list)
    confidence: str = "medium"  # "high" | "medium" | "low"
    # confidence reflects whether the task fields could be unambiguously
    # extracted from the source; it is NOT a judgement of scientific quality.
    created_at: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )


class ResourceCard(BaseModel):
    """A resource referenced by a protocol.

    Resources include tools, databases, reference genomes, software packages,
    containers, and websites.  Version and installation info are ONLY filled
    when the source document explicitly provides them.
    """

    resource_id: str
    protocol_id: str
    resource_name: str
    resource_type: str = "other"
    # "tool", "database", "software", "package", "workflow",
    # "container", "website", "other"
    version: str = ""
    purpose: str = ""
    installation_info: str = ""
    evidence_spans: list[EvidenceSpan] = Field(default_factory=list)
    notes: list[str] = Field(default_factory=list)
    created_at: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )


class ReplicationPlan(BaseModel):
    """A structured plan for reproducing a bioinformatics study.

    Generated by the agent after reviewing all evidence for one or more
    protocols.  It explicitly separates what can be automated, what needs
    manual confirmation, and what blocks execution entirely.
    """

    plan_id: str
    protocol_ids: list[str] = Field(default_factory=list)
    research_goal: str = ""
    required_inputs: list[str] = Field(default_factory=list)
    expected_outputs: list[str] = Field(default_factory=list)
    tasks: list[TaskCard] = Field(default_factory=list)
    resources: list[ResourceCard] = Field(default_factory=list)
    missing_information: list[str] = Field(default_factory=list)
    automatable_steps: list[str] = Field(default_factory=list)
    manual_confirmation_required: list[str] = Field(default_factory=list)
    cannot_proceed_reasons: list[str] = Field(default_factory=list)
    evidence_summary: list[EvidenceSpan] = Field(default_factory=list)
    created_at: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )
