"""Audit event names used by BioCoreAgent."""

from enum import StrEnum


class EventType(StrEnum):
    USER_MESSAGE = "USER_MESSAGE"
    LLM_REQUEST = "LLM_REQUEST"
    LLM_RESPONSE = "LLM_RESPONSE"
    TOOL_CALL = "TOOL_CALL"
    TOOL_RESULT = "TOOL_RESULT"
    FILE_READ = "FILE_READ"
    FILE_WRITE = "FILE_WRITE"
    FILE_EDIT = "FILE_EDIT"
    COMMAND_RUN = "COMMAND_RUN"
    CONTEXT_COMPRESS = "CONTEXT_COMPRESS"
    SESSION_SAVE = "SESSION_SAVE"
    POLICY_BLOCK = "POLICY_BLOCK"
    ERROR = "ERROR"
